# yaml

# server to server
- location: /realtime/access-tokens/
  description: access tokens
  hide_document: true
  allow:
    - 127.0.0.1/32
    - 192.168.0.0/16
    - 172.16.0.0/12
  middlewares:
    - AuthRoot            # superuser authorization
    - HybsLog             # hybs system log
    - Authentication      # parse header and basic authentication
    - ResponseJSON        # response json content-type
    - UseCache            # use cache mux named Cache
    - UseRedis            # use redis conn named Redis
  const_params:
    - name: app_name
      value: sample-game
    - name: cache_id
      value: Cache
    - name: redis_id
      value: Redis
  services:
    - method: POST
      description: generate and return access token
      service_id: RealtimeCreateAccessTokenV1