# yaml

app_name: sample-platform-server
version: 0.0.0
env: local
app_config: config/application.yml
debug_mode: true
display_logo: true

redis:
  - id: Redis
    network: tcp
    address: localhost:6389
    db: 0
    dial_timeout: 2s
    read_timeout: 2s
    write_timeout: 2s
    min_idle_conns: 2
    pool_size: 50 # default CPU number*10

mongodb:
  - id: MongoPlatform
    hosts:
      - localhost:27117
    database: hybs_platform
    auth_source: admin
    username: root
    password: hayabusa-cloud
    min_pool_size: 2
    max_pool_size: 50
    max_conn_idle_time: 15m
    connect_timeout: 2s
    server_selection_timeout: 2s
    socket_timeout: 2s
    compression_level: 0

http_server:
  - id: platform-local
    http_version: 1.1
    network: tcp
    address: localhost:8086
    use_tls: false
    read_timeout: 5s
    write_timeout: 1s
    compress_level: 1
    controller_filepath: config/service-platform/
