# yaml

app_name: sample-game-gate
version: 0.0.0
env: local
app_config: config/application.yml
debug_mode: true
display_logo: true

lb_client:
  - id: sample-client01
    scheme: http
    host: localhost
    port: 8087
  - id: sample-client02
    scheme: http
    host: localhost
    port: 8089

http_gate:
  - id: sample-gate-local
    http_version: 1.1
    network: tcp
    address: localhost:8088
    use_tls: false
    read_timeout: 5s
    write_timeout: 1s
    gateways:
      - server_name: "*" # "*" accepts any hostname
    # - server_name: games.api.my-domain-name.co.jp
        lb_clients:
          # clients group
          - sample-client01
          - sample-client02